apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-skrivestotte
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  image: "{{ image }}"
  port: 7070
  liveness:
    path: /modiapersonoversikt-skrivestotte/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-skrivestotte/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-skrivestotte/internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modiapersonoversikt-skrivestotte.intern.dev.nav.no
    - https://modiapersonoversikt-skrivestotte.ansatt.dev.nav.no
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-f1-micro
        databases:
          - name: modiapersonoversikt-skrivestotte-db
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: dev-gcp

  leaderElection: true
  webproxy: true
  env:
    - name: DB_NAME
      value: "modiapersonoversikt-skrivestotte-db"
    - name: USE_STATISTICS_SORT
      value: "true"
    - name: BASE_PATH
      value: ""
