apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-skrivestotte
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: {{ image }}
  port: 7070
  webproxy: true
  liveness:
    path: /modiapersonoversikt-skrivestotte/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-skrivestotte/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-skrivestotte/internal/metrics
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modiapersonoversikt-skrivestotte.intern.dev.nav.no
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: modiapersonoversikt-skrivestotte-db
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: dev-gcp
        - application: modiapersonoversikt-q0
          namespace: personoversikt
          cluster: dev-fss
        - application: modiapersonoversikt-q1
          namespace: personoversikt
          cluster: dev-fss

  leaderElection: true
  env:
    - name: DB_NAME
      value: "modiapersonoversikt-skrivestotte-db"
    - name: USE_STATISTICS_SORT
      value: "true"
