apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-skrivestotte
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 7070
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modiapersonoversikt-skrivestotte.intern.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-custom-1-3840
        databases:
          - name: modiapersonoversikt-skrivestotte-db
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: prod-gcp
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: prod-fss
  leaderElection: true
  env:
    - name: USE_STATISTICS_SORT
      value: "true"
    - name: DB_NAME
      value: "modiapersonoversikt-skrivestotte-db"
    - name: BASE_PATH
      value: ""
