apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-skrivestotte
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: {{ image }}
  port: 7070
  webproxy: true
  team: personoversikt
  liveness:
    path: /modiapersonoversikt-skrivestotte/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-skrivestotte/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-skrivestotte/internal/metrics
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://app-q0.adeo.no/modiapersonoversikt-skrivestotte
    - https://app-q1.adeo.no/modiapersonoversikt-skrivestotte
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt-q0
          namespace: personoversikt
          cluster: dev-fss
        - application: modiapersonoversikt-q1
          namespace: personoversikt
          cluster: dev-fss
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  leaderElection: true
  env:
    - name: ISSO_JWKS_URL
      value: "https://isso-q.adeo.no/isso/oauth2/connect/jwk_uri"
    - name: ISSO_ISSUER
      value: "https://isso-q.adeo.no:443/isso/oauth2"
    - name: DATABASE_JDBC_URL
      value: "jdbc:postgresql://b27dbvl008.preprod.local:5432/modiapersonoversikt-skrivestotte"
    - name: VAULT_MOUNTPATH
      value: "postgresql/preprod-fss"
    - name: USE_STATISTICS_SORT
      value: "true"
