apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-skrivestotte
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "navikt/modiapersonoversikt-skrivestotte:{{version}}"
  port: 7070
  team: personoversikt
  liveness:
    path: /isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://modiapersonoversikt-skrivestotte.nais.preprod.local
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  env:
    - name: SECURITY_TOKEN_SERVICE_JWKS_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/jwks
    - name: SECURITY_TOKEN_SERVICE_ISSUER
      value: https://security-token-service.nais.preprod.local
    - name: S3_URL
      value: s3.nais.preprod.local
    - name: S3_REGION
      value: us-east-1
